/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tfg;

import static com.mycompany.tfg.AccesoBarpibas.obtenerDatosClientePorCorreo;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author isard
 */
public class Ventana_Menu extends javax.swing.JFrame {
    /**
     * Creates new form Ventana_Menu
     */
    public String correoUsuario;
    public Ventana_Menu(String correo) {
        initComponents();
        this.correoUsuario = correo;
        ImageIcon imagen = new ImageIcon(getClass().getResource("/flecha.png"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabelVolver.getWidth(), jLabelVolver.getHeight(), Image.SCALE_DEFAULT));
        jLabelVolver.setIcon(icono);
    }
    
    public Ventana_Menu() {
        initComponents();
        ImageIcon imagen = new ImageIcon(getClass().getResource("/flecha.png"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabelVolver.getWidth(), jLabelVolver.getHeight(), Image.SCALE_DEFAULT));
        jLabelVolver.setIcon(icono);
    }

    private Cliente cliente;

    public Ventana_Menu(Cliente cliente) {
        this.cliente = cliente;
        ImageIcon imagen = new ImageIcon(getClass().getResource("/flecha.png"));
        Icon icono = new ImageIcon(imagen.getImage().getScaledInstance(jLabelVolver.getWidth(), jLabelVolver.getHeight(), Image.SCALE_DEFAULT));
        jLabelVolver.setIcon(icono);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPerfil = new javax.swing.JButton();
        jLabelRegistro = new javax.swing.JLabel();
        jButtonRegistro = new javax.swing.JButton();
        jButtoncerrar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jLabelVolver = new javax.swing.JLabel();
        jLabelPerfil = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPerfil.setText("Ver Mas");
        jButtonPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPerfilActionPerformed(evt);
            }
        });

        jLabelRegistro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelRegistro.setText("Registro Compras");

        jButtonRegistro.setText("Ver Mas");

        jButtoncerrar.setText("Cerrar Sesión");
        jButtoncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncerrarActionPerformed(evt);
            }
        });

        jButtonBorrar.setText("Borrar Cuenta");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jLabelVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/flecha.png"))); // NOI18N
        jLabelVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelVolverMouseClicked(evt);
            }
        });

        jLabelPerfil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelPerfil.setText("Mi Perfil");

        jButton1.setText("Contacto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButtonPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabelRegistro))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButtonBorrar))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButtoncerrar))
            .addGroup(layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jLabelPerfil))
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jButtonRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jButtonPerfil)
                .addGap(27, 27, 27)
                .addComponent(jLabelRegistro)
                .addGap(125, 125, 125)
                .addComponent(jButtonBorrar))
            .addGroup(layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addComponent(jButtoncerrar))
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelPerfil))
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButton1))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jButtonRegistro))
            .addComponent(jLabelFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelVolverMouseClicked
        Ventana_Inicio vi = new Ventana_Inicio(correoUsuario);
        vi.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabelVolverMouseClicked

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        Ventana_BorrarCuenta vbc = new Ventana_BorrarCuenta(correoUsuario);
        vbc.setVisible(true);
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jButtoncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncerrarActionPerformed
        dispose();
        Ventana_Inicio vi = new Ventana_Inicio(correoUsuario);
        vi.setVisible(true);
    }//GEN-LAST:event_jButtoncerrarActionPerformed

    private void jButtonPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPerfilActionPerformed
        Cliente datos = AccesoBarpibas.obtenerDatosClientePorCorreo(correoUsuario);
    if (datos != null) {
    String mensaje = "Nombre: " + datos.getNombre() + 
                     "\nApellidos: " + datos.getApellidos() + 
                     "\nDNI: " + datos.getDni() + 
                     "\nCorreo: " + datos.getCorreo();
    JOptionPane.showMessageDialog(null, mensaje);
}
    else{
        JOptionPane.showMessageDialog(null, "No hay datos ya que no iniciaste sesión.", "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButtonPerfilActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Ventana_Contacto vc = new Ventana_Contacto(correoUsuario);
        vc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonPerfil;
    private javax.swing.JButton jButtonRegistro;
    private javax.swing.JButton jButtoncerrar;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelPerfil;
    private javax.swing.JLabel jLabelRegistro;
    private javax.swing.JLabel jLabelVolver;
    // End of variables declaration//GEN-END:variables
}
